AllCops:
  Exclude:
    - aggro.gemspec
    - lib/aggro/version.rb

Documentation:
  Exclude:
    - spec/**/*

Eval:
  Exclude:
    - spec/spec_helper.rb

RaiseArgs:
  Exclude:
    - lib/aggro/nanomsg_transport/connection.rb
