language: ruby
rvm:
  - 2.2.0
  - jruby-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
script: bundle exec rspec
before_install: sudo apt-get install libzmq3-dev
