language: ruby
rvm:
  - 2.2.0
  - jruby-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
script: bundle exec rspec
before_install:
  - git clone git://github.com/nanomsg/nanomsg.git
  - cd nanomsg && ./autogen.sh && ./configure && sudo make install && sudo ldconfig && cd ${TRAVIS_BUILD_DIR}
