language: ruby
rvm:
  - 2.2.0
  - ruby-head
  - jruby-head
script: bundle exec rspec
before_install:
  - git clone git://github.com/nanomsg/nanomsg.git
  - cd nanomsg && ./autogen.sh && ./configure --enable-debug && sudo make install && sudo ldconfig && cd ${TRAVIS_BUILD_DIR}
